name: house_hunt
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotlipy=0.7.0=py310h1961e1f_1004
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.9.24=h033912b_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h96bbf6e_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310h2ec42d9_0
  - cryptography=37.0.1=py310hf6deb26_0
  - debugpy=1.6.3=py310h154be8b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.0.0=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.15.3=pyh736e0ef_0
  - ipython=8.5.0=pyhd1c38e8_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310h2ec42d9_0
  - libblas=3.9.0=16_osx64_openblas
  - libcblas=3.9.0=16_osx64_openblas
  - libcxx=14.0.6=hccf4f1f_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=10_4_0_h97931a8_25
  - libgfortran5=11.3.0=h082f757_25
  - liblapack=3.9.0=16_osx64_openblas
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.39.3=ha978bb4_0
  - libzlib=1.2.12=hfd90126_3
  - llvm-openmp=14.0.4=ha654fa7_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - numpy=1.23.3=py310h1b7c290_0
  - openssl=3.0.5=hfd90126_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.0=py310hecf8f37_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py310h90acd4f_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=hc14f532_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=0.21.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyzmq=24.0.1=py310hf615a82_0
  - readline=8.1.2=h3899abd_0
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=65.3.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.2=py310h6c45266_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - tzdata=2022c=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - zeromq=4.3.4=he49afe7_1
prefix: /usr/local/Caskroom/miniconda/base/envs/house_hunt
